language: node_js
node_js:
  - "node"

os:
  # Guarantee that the "cp" below in before_deploy exists and works
  # (Might as well be Mac OS X; in any case not Windows where "cp" is
  #  named "copy".)
  - linux

script: npm test
after_success: npm run coverage

before_deploy:
  - npm run build-docs
  - "cp -a ./coverage ./docs"

deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages

  # Fix https://github.com/travis-ci/travis-ci/issues/9312#issuecomment-371590249
  edge:
    branch: v1.8.47
