name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages (with caching)
        uses: bahmutov/npm-install@v1.7.1
      - name: Run tests
        run: npm test
      - name: Generate and publish coverage reports on coveralls.io
        run: npm run coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Copy coverage reports to deployment folder
        run: mkdir ./deploy && cp -a ./coverage ./deploy
      - name: Build documentation
        run: npm run build-docs
      - name: Copy documentation to deployment folder
        run: cp -a ./docs ./deploy
      - name: Publish documentation to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
